/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SistemasRouteImport } from './routes/sistemas'
import { Route as DisenoWebRouteImport } from './routes/diseno-web'
import { Route as IndexRouteImport } from './routes/index'

const SistemasRoute = SistemasRouteImport.update({
  id: '/sistemas',
  path: '/sistemas',
  getParentRoute: () => rootRouteImport,
} as any)
const DisenoWebRoute = DisenoWebRouteImport.update({
  id: '/diseno-web',
  path: '/diseno-web',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diseno-web': typeof DisenoWebRoute
  '/sistemas': typeof SistemasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diseno-web': typeof DisenoWebRoute
  '/sistemas': typeof SistemasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diseno-web': typeof DisenoWebRoute
  '/sistemas': typeof SistemasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diseno-web' | '/sistemas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diseno-web' | '/sistemas'
  id: '__root__' | '/' | '/diseno-web' | '/sistemas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisenoWebRoute: typeof DisenoWebRoute
  SistemasRoute: typeof SistemasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sistemas': {
      id: '/sistemas'
      path: '/sistemas'
      fullPath: '/sistemas'
      preLoaderRoute: typeof SistemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseno-web': {
      id: '/diseno-web'
      path: '/diseno-web'
      fullPath: '/diseno-web'
      preLoaderRoute: typeof DisenoWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisenoWebRoute: DisenoWebRoute,
  SistemasRoute: SistemasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
