/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TkRouteImport } from './routes/tk'
import { Route as SistemasRouteImport } from './routes/sistemas'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as MentoriaRouteImport } from './routes/mentoria'
import { Route as DisenoWebRouteImport } from './routes/diseno-web'
import { Route as IndexRouteImport } from './routes/index'

const TkRoute = TkRouteImport.update({
  id: '/tk',
  path: '/tk',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemasRoute = SistemasRouteImport.update({
  id: '/sistemas',
  path: '/sistemas',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoriaRoute = MentoriaRouteImport.update({
  id: '/mentoria',
  path: '/mentoria',
  getParentRoute: () => rootRouteImport,
} as any)
const DisenoWebRoute = DisenoWebRouteImport.update({
  id: '/diseno-web',
  path: '/diseno-web',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diseno-web': typeof DisenoWebRoute
  '/mentoria': typeof MentoriaRoute
  '/servicios': typeof ServiciosRoute
  '/sistemas': typeof SistemasRoute
  '/tk': typeof TkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diseno-web': typeof DisenoWebRoute
  '/mentoria': typeof MentoriaRoute
  '/servicios': typeof ServiciosRoute
  '/sistemas': typeof SistemasRoute
  '/tk': typeof TkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diseno-web': typeof DisenoWebRoute
  '/mentoria': typeof MentoriaRoute
  '/servicios': typeof ServiciosRoute
  '/sistemas': typeof SistemasRoute
  '/tk': typeof TkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/diseno-web' | '/mentoria' | '/servicios' | '/sistemas' | '/tk'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diseno-web' | '/mentoria' | '/servicios' | '/sistemas' | '/tk'
  id:
    | '__root__'
    | '/'
    | '/diseno-web'
    | '/mentoria'
    | '/servicios'
    | '/sistemas'
    | '/tk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisenoWebRoute: typeof DisenoWebRoute
  MentoriaRoute: typeof MentoriaRoute
  ServiciosRoute: typeof ServiciosRoute
  SistemasRoute: typeof SistemasRoute
  TkRoute: typeof TkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tk': {
      id: '/tk'
      path: '/tk'
      fullPath: '/tk'
      preLoaderRoute: typeof TkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas': {
      id: '/sistemas'
      path: '/sistemas'
      fullPath: '/sistemas'
      preLoaderRoute: typeof SistemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentoria': {
      id: '/mentoria'
      path: '/mentoria'
      fullPath: '/mentoria'
      preLoaderRoute: typeof MentoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseno-web': {
      id: '/diseno-web'
      path: '/diseno-web'
      fullPath: '/diseno-web'
      preLoaderRoute: typeof DisenoWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisenoWebRoute: DisenoWebRoute,
  MentoriaRoute: MentoriaRoute,
  ServiciosRoute: ServiciosRoute,
  SistemasRoute: SistemasRoute,
  TkRoute: TkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
